# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ValStressTest.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(190, 30, 1280, 800))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.treeWidget.setFont(font)
        self.treeWidget.setAutoFillBackground(True)
        self.treeWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.treeWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.treeWidget.setAutoScroll(False)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.treeWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setDefaultSectionSize(300)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setMinimumSectionSize(300)
        self.horizontalLayout.addWidget(self.treeWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.comboBox.setFont(font)
        self.comboBox.setAutoFillBackground(True)
        self.comboBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.Button_start = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.Button_start.setFont(font)
        self.Button_start.setAutoFillBackground(True)
        self.Button_start.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Button_start.setObjectName("Button_start")
        self.verticalLayout.addWidget(self.Button_start)
        self.Button_stop = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.Button_stop.setFont(font)
        self.Button_stop.setAutoFillBackground(True)
        self.Button_stop.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Button_stop.setObjectName("Button_stop")
        self.verticalLayout.addWidget(self.Button_stop)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setAutoFillBackground(True)
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 2)
        self.label_logcat = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_logcat.setFont(font)
        self.label_logcat.setAutoFillBackground(True)
        self.label_logcat.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_logcat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_logcat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_logcat.setObjectName("label_logcat")
        self.gridLayout.addWidget(self.label_logcat, 1, 0, 1, 1)
        self.label_current_step = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_current_step.setFont(font)
        self.label_current_step.setAutoFillBackground(True)
        self.label_current_step.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_current_step.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_current_step.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_current_step.setObjectName("label_current_step")
        self.gridLayout.addWidget(self.label_current_step, 1, 1, 1, 1)
        self.Logcat = QtWidgets.QTextBrowser(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.Logcat.setFont(font)
        self.Logcat.setAutoFillBackground(True)
        self.Logcat.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Logcat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Logcat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Logcat.setObjectName("Logcat")
        self.gridLayout.addWidget(self.Logcat, 2, 0, 1, 1)
        self.Step_Log = QtWidgets.QTextBrowser(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.Step_Log.setFont(font)
        self.Step_Log.setAutoFillBackground(True)
        self.Step_Log.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Step_Log.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Step_Log.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Step_Log.setObjectName("Step_Log")
        self.gridLayout.addWidget(self.Step_Log, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.progressBar.raise_()
        self.comboBox.raise_()
        self.Button_start.raise_()
        self.Button_stop.raise_()
        self.treeWidget.raise_()
        self.progressBar.raise_()
        self.Logcat.raise_()
        self.Step_Log.raise_()
        self.label_current_step.raise_()
        self.label_logcat.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1388, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Test Item"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Parameter"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.comboBox.setItemText(0, _translate("MainWindow", "Android 7"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Android 8"))
        self.Button_start.setText(_translate("MainWindow", "Start"))
        self.Button_stop.setText(_translate("MainWindow", "Stop"))
        self.label_logcat.setText(_translate("MainWindow", "logcat"))
        self.label_current_step.setText(_translate("MainWindow", "current step"))

